### ISSUE TITLE
Unhandled exception with --clip option

### ISSUE THREAD

**Issue by a1exsh** [zalando-stups/piu#11]
``` sh
$ piu request-access -t 1 --clip 172.31.171.204 test shell history
Requesting access to host 172.31.171.204 via odd-... for oshulgin..
Access to host odd-.../xx.xx.xxx.xxx for user oshulgin was granted.
You can now access your server with the following command:
...

Or just check your clipboard and run ctrl/command + v (requires package "xclip" on Linux)
Traceback (most recent call last):
  File "/home/oshulgin/.local/bin/piu", line 11, in <module>
    sys.exit(main())
  File "/home/oshulgin/.local/lib/python3.5/site-packages/piu/cli.py", line 305, in main
    cli()
  File "/home/oshulgin/.local/lib/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/oshulgin/.local/lib/python3.5/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/oshulgin/.local/lib/python3.5/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/oshulgin/.local/lib/python3.5/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/oshulgin/.local/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/oshulgin/.local/lib/python3.5/site-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/home/oshulgin/.local/lib/python3.5/site-packages/piu/cli.py", line 260, in request_access
    user, password, clip)
  File "/home/oshulgin/.local/lib/python3.5/site-packages/piu/cli.py", line 159, in _request_access
    pyperclip.copy(command)
  File "/home/oshulgin/.local/lib/python3.5/site-packages/pyperclip/clipboards.py", line 32, in copy_gtk
    cb = gtk.Clipboard()
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 62, in __getattr__
    raise AttributeError(_static_binding_error)
AttributeError: When using gi.repository you must not import static modules like "gobject". Please change all occurrences of "import gobject" to "from gi.repository import GObject". See: https://bugzilla.gnome.org/show_bug.cgi?id=709183
```

**Comment by hjacobs** [comment]
Looks like a bug in the `pyperclip` Python module..

**Comment by hjacobs** [comment]
@a1exsh maybe you can check your `pyperclip` version (pip3 freeze) and report the issue here: https://github.com/asweigart/pyperclip/issues

**Comment by hjacobs** [comment]
I get the same problem (Xubuntu 15.10):

```
$ piu 172.31.1.1 test https://github.com/zalando-stups/piu/issues/11 --clip
Requesting access to host 172.31.1.1 via odd-eu-XXX for hjacobs..
Access to host odd-eu-XXX for user hjacobs was granted.
You can now access your server with the following command:
ssh -tA hjacobs@odd-eu-XXX ssh -o StrictHostKeyChecking=no hjacobs@172.31.1.1

Or just check your clipboard and run ctrl/command + v (requires package "xclip" on Linux)
Traceback (most recent call last):
  File "/usr/local/bin/piu", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.4/dist-packages/piu/cli.py", line 305, in main
    cli()
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/piu/cli.py", line 260, in request_access
    user, password, clip)
  File "/usr/local/lib/python3.4/dist-packages/piu/cli.py", line 159, in _request_access
    pyperclip.copy(command)
  File "/usr/local/lib/python3.4/dist-packages/pyperclip/clipboards.py", line 32, in copy_gtk
    cb = gtk.Clipboard()
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 62, in __getattr__
    raise AttributeError(_static_binding_error)
AttributeError: When using gi.repository you must not import static modules like "gobject". Please change all occurrences of "import gobject" to "from gi.repository import GObject". See: https://bugzilla.gnome.org/show_bug.cgi?id=709183
$ pip3 freeze | grep pyperclip
pyperclip==1.5.25
$ python3 --version
Python 3.4.3+

```

**Comment by a1exsh** [comment]
I've got the same versions (Ubuntu Gnome 15.10), pyperclip 1.5.25, python 3.4.3+.  However if I try it with interactive python prompt, it appears to work:

``` py
>>> import pyperclip
>>> pyperclip.copy('test')
```

Actually, that works only with python3.5, not 3.4.  All the 3 packages installed with `pip3` go to python3.5 on my system.

**Comment by szuecs** [comment]
Is this issue resolved or what can we do to resolve it?
Maybe adding some documentation that this feature only works with pyperclip version xyz?

**Comment by outime** [comment]
If this is still an issue (can't say as I can't reproduce) perhaps `--connect` alone could work for some use cases as it directly connects you to the instance so you can skip the copy-pasting part.

**Comment by a1exsh** [comment]
I'm mostly using `--connect` these days.

**Comment by hjacobs** [comment]
I guess we can remove the `--clip` option completely.

**Comment by szuecs** [comment]
If nobody answers, with "No I am using --clip" in the next days we will remove it.
